import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedchatwidget/generated/GeneratedMenuChatWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedchatwidget/generated/GeneratedNewMatchesWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedchatwidget/generated/GeneratedMessagesWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedchatwidget/generated/GeneratedPopupWidget3.dart';
import 'package:flutterapp/taffy_appapp/generatedchatwidget/generated/GeneratedPopupWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatedchatwidget/generated/GeneratedRectangle239Widget2.dart';
import 'package:flutterapp/taffy_appapp/generatedchatwidget/generated/GeneratedMdi_searchWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedchatwidget/generated/GeneratedMdi_textsmsWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedchatwidget/generated/GeneratedDiscoverWidget1.dart';
import 'package:flutterapp/taffy_appapp/generatedchatwidget/generated/GeneratedMenuWidget1.dart';

/* Frame Chat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: -44.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 290.0,
                child: GeneratedRectangle239Widget2(),
              ),
              Positioned(
                left: 91.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 54.0,
                child: GeneratedDiscoverWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedMdi_textsmsWidget(),
              ),
              Positioned(
                left: 320.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedMdi_searchWidget(),
              ),
              Positioned(
                left: -1.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 375.97674560546875,
                height: 584.0,
                child: GeneratedPopupWidget2(),
              ),
              Positioned(
                left: -1.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 614.0,
                child: GeneratedPopupWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.912;

                  final double height =
                      constraints.maxHeight * 0.09654607913764239;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.056,
                        y: constraints.maxHeight * 0.2204433497536946,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNewMatchesWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 20.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 599.0,
                child: GeneratedMessagesWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.912;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.048,
                        y: constraints.maxHeight * 0.1416256157635468,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMenuChatWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 73.0,
                child: GeneratedMenuWidget1(),
              )
            ]),
      ),
    ));
  }
}
