import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedPhoto3Widget.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedMenuWidget5.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedBackgroundWidget.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedCillistfilterWidget3.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedCillistfilterWidget1.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedDiscoverWidget8.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedMdi_filter_listWidget.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedMdi_filter_listWidget2.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedMdi_find_replaceWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedCillistfilterWidget.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedCillistfilterWidget2.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedCillistfilterWidget4.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedButtonsWidget.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedMdi_filter_listWidget3.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedMdi_filter_listWidget1.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedCillistfilterWidget5.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedPhoto2Widget.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedGroup35Widget.dart';
import 'package:flutterapp/taffy_appapp/generateddiscovergoldwidget/generated/GeneratedVectorWidget136.dart';

/* Frame DiscoverGold
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDiscoverGoldWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 344.0,
                child: GeneratedBackgroundWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 296.0,
                height: 447.0,
                child: GeneratedPhoto3Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 430.0,
                child: GeneratedPhoto2Widget(),
              ),
              Positioned(
                left: 73.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 54.0,
                child: GeneratedDiscoverWidget8(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget1(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget1(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget2(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget3(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget2(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget4(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget5(),
              ),
              Positioned(
                left: 36.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 560.3469848632812,
                child: GeneratedGroup35Widget(),
              ),
              Positioned(
                left: 305.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 331.0,
                child: GeneratedButtonsWidget(),
              ),
              Positioned(
                left: 314.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedMdi_filter_listWidget3(),
              ),
              Positioned(
                left: 21.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedMdi_find_replaceWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.050666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 19.0;

                  double percentHeight = 0.023399014778325122;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8746666666666667,
                        translateY: constraints.maxHeight * 0.4396551724137931,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget136())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 73.0,
                child: GeneratedMenuWidget5(),
              )
            ]),
      ),
    ));
  }
}
