import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedview_profile2widget/generated/GeneratedPageHeaderWidget1.dart';
import 'package:flutterapp/taffy_appapp/generatedview_profile2widget/generated/GeneratedContentContentBlockLargeWidget9.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatedview_profile2widget/generated/GeneratedRectangle239Widget9.dart';
import 'package:flutterapp/taffy_appapp/generatedview_profile2widget/generated/GeneratedGroup72Widget1.dart';

/* Frame View_Profile2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedView_Profile2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: -20.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 300.0,
                child: GeneratedRectangle239Widget9(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget1(),
              ),
              Positioned(
                left: null,
                top: 126.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 646.0,
                child: TransformHelper.translate(
                    x: 2.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedContentContentBlockLargeWidget9()),
              ),
              Positioned(
                left: 304.0,
                top: 635.0,
                right: null,
                bottom: null,
                width: 53.099998474121094,
                height: 54.0,
                child: GeneratedGroup72Widget1(),
              )
            ]),
      ),
    ));
  }
}
