import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedview_profilewidget/generated/GeneratedContentContentBlockSmallWidget5.dart';
import 'package:flutterapp/taffy_appapp/generatedview_profilewidget/generated/GeneratedNameBioWidget1.dart';
import 'package:flutterapp/taffy_appapp/generatedview_profilewidget/generated/GeneratedGroup67Widget.dart';
import 'package:flutterapp/taffy_appapp/generatedview_profilewidget/generated/GeneratedPageHeaderWidget2.dart';
import 'package:flutterapp/taffy_appapp/generatedview_profilewidget/generated/GeneratedSegmentedControlLeftWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedview_profilewidget/generated/GeneratedContentContentBlockSmallWidget1.dart';
import 'package:flutterapp/taffy_appapp/generatedview_profilewidget/generated/GeneratedContentContentBlockSmallWidget2.dart';
import 'package:flutterapp/taffy_appapp/generatedview_profilewidget/generated/GeneratedContentContentBlockSmallWidget4.dart';
import 'package:flutterapp/taffy_appapp/generatedview_profilewidget/generated/GeneratedRectangle239Widget10.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatedview_profilewidget/generated/GeneratedContentContentBlockSmallWidget3.dart';

/* Frame View_Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedView_ProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: -34.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 285.0,
                child: GeneratedRectangle239Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.456;

                  final double height =
                      constraints.maxHeight * 0.2105911330049261;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2826666666666667,
                        y: constraints.maxHeight * 0.16133004926108374,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup67Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget2(),
              ),
              Positioned(
                left: 64.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 63.0,
                child: GeneratedNameBioWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 389.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedSegmentedControlLeftWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 455.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 635.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 725.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget3(),
              ),
              Positioned(
                left: 18.0,
                top: 812.0,
                right: 14.0,
                bottom: null,
                width: null,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget4(),
              ),
              Positioned(
                left: 18.0,
                top: 545.0,
                right: 14.0,
                bottom: null,
                width: null,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget5(),
              )
            ]),
      ),
    ));
  }
}
