import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedpopupwidget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/taffy_appapp/generatedpopupwidget/generated/GeneratedTextWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedpopupwidget/generated/GeneratedBGWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedpopupwidget/generated/GeneratedButtonPrimaryWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedpopupwidget/generated/GeneratedDontliketheappLetusknowWidget.dart';

/* Group Popup
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPopupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 343.0,
      height: 427.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 427.0,
              child: GeneratedBGWidget(),
            ),
            Positioned(
              left: 76.0,
              top: 32.0,
              right: null,
              bottom: null,
              width: 192.0,
              height: 32.0,
              child: GeneratedGroup18Widget(),
            ),
            Positioned(
              left: 16.0,
              top: 307.0,
              right: null,
              bottom: null,
              width: 311.0,
              height: 51.0,
              child: GeneratedButtonPrimaryWidget(),
            ),
            Positioned(
              left: 16.0,
              top: 376.0,
              right: null,
              bottom: null,
              width: 313.0,
              height: 21.0,
              child: GeneratedDontliketheappLetusknowWidget(),
            ),
            Positioned(
              left: 16.0,
              top: 96.0,
              right: null,
              bottom: null,
              width: 311.0,
              height: 166.0,
              child: GeneratedTextWidget(),
            )
          ]),
    ));
  }
}
