import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget54/generated/GeneratedWidget55.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget54/generated/GeneratedMdi_verified_userWidget6.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget54/generated/GeneratedVectorWidget211.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget54/generated/GeneratedBaseWidget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget54/generated/GeneratedMdi_checkWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget54/generated/GeneratedGroup65Widget6.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget54/generated/GeneratedPopupWidget21.dart';

/* Frame ฉันเป็นเพศ
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget54 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -30.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 842.0,
                child: GeneratedBaseWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 768.0,
                child: GeneratedPopupWidget21(),
              ),
              Positioned(
                left: 77.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 34.0,
                child: GeneratedWidget55(),
              ),
              Positioned(
                left: 16.5,
                top: 117.0,
                right: null,
                bottom: null,
                width: 343.5,
                height: 196.0,
                child: GeneratedGroup65Widget6(),
              ),
              Positioned(
                left: 63.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_verified_userWidget6(),
              ),
              Positioned(
                left: 188.25,
                top: 215.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_checkWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04690666707356771;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 17.59000015258789;

                  double percentHeight = 0.01651477813720703;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      13.40999984741211;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.864,
                        translateY: constraints.maxHeight * 0.1625615763546798,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget211())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
