import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedDiscoverWidget12.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedCillistfilterWidget26.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedButtonsWidget4.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedPhoto2Widget4.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedVectorWidget174.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedMenuWidget9.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedPhoto3Widget4.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedMdi_filter_listWidget16.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedMdi_filter_listWidget17.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedBackgroundWidget4.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedCillistfilterWidget28.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedMdi_filter_listWidget19.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedCillistfilterWidget29.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedBrokenheartWidget2.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedCillistfilterWidget27.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedCillistfilterWidget25.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedGroup79Widget.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedCillistfilterWidget24.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedGroup35Widget4.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedMdi_find_replaceWidget4.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedMdi_filter_listWidget18.dart';
import 'package:flutterapp/taffy_appapp/generatednope_likewidget/generated/GeneratedFlatcoloriconsdislikeWidget.dart';

/* Frame nope_Like
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNope_LikeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 344.0,
                child: GeneratedBackgroundWidget4(),
              ),
              Positioned(
                left: 43.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 296.0,
                height: 447.0,
                child: GeneratedPhoto3Widget4(),
              ),
              Positioned(
                left: 39.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 430.0,
                child: GeneratedPhoto2Widget4(),
              ),
              Positioned(
                left: 73.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 54.0,
                child: GeneratedDiscoverWidget12(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget16(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget24(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget25(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget17(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget26(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget27(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget18(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget28(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget29(),
              ),
              Positioned(
                left: 36.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 560.3469848632812,
                child: GeneratedGroup35Widget4(),
              ),
              Positioned(
                left: 90.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 195.0,
                height: 63.0,
                child: GeneratedGroup79Widget(),
              ),
              Positioned(
                left: 107.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 169.0,
                child: GeneratedFlatcoloriconsdislikeWidget(),
              ),
              Positioned(
                left: 305.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 331.0,
                child: GeneratedButtonsWidget4(),
              ),
              Positioned(
                left: 314.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedMdi_filter_listWidget19(),
              ),
              Positioned(
                left: 21.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedMdi_find_replaceWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.050666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 19.0;

                  double percentHeight = 0.023399014778325122;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8746666666666667,
                        translateY: constraints.maxHeight * 0.4396551724137931,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget174())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.22308101399739583;

                  final double height =
                      constraints.maxHeight * 0.0924061178573834;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.42133333333333334,
                        y: constraints.maxHeight * 0.16133004926108374,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBrokenheartWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 73.0,
                child: GeneratedMenuWidget9(),
              )
            ]),
      ),
    ));
  }
}
