import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedaddprofilewidget/generated/GeneratedPopupWidget15.dart';
import 'package:flutterapp/taffy_appapp/generatedaddprofilewidget/generated/GeneratedMdi_verified_userWidget1.dart';
import 'package:flutterapp/taffy_appapp/generatedaddprofilewidget/generated/GeneratedWidget34.dart';
import 'package:flutterapp/taffy_appapp/generatedaddprofilewidget/generated/GeneratedMdi_linkWidget1.dart';
import 'package:flutterapp/taffy_appapp/generatedaddprofilewidget/generated/GeneratedBaseWidget1.dart';
import 'package:flutterapp/taffy_appapp/generatedaddprofilewidget/generated/GeneratedHttpswwwgooglecomWidget1.dart';
import 'package:flutterapp/taffy_appapp/generatedaddprofilewidget/generated/GeneratedGroup65Widget1.dart';

/* Frame ADDPROFILE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedADDPROFILEWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -30.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 842.0,
                child: GeneratedBaseWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 768.0,
                child: GeneratedPopupWidget15(),
              ),
              Positioned(
                left: 76.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 34.0,
                child: GeneratedWidget34(),
              ),
              Positioned(
                left: 15.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 157.0,
                child: GeneratedGroup65Widget1(),
              ),
              Positioned(
                left: 63.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 27.0,
                child: GeneratedHttpswwwgooglecomWidget1(),
              ),
              Positioned(
                left: 63.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_verified_userWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 173.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_linkWidget1(),
              )
            ]),
      ),
    ));
  }
}
