import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generateddetailmessageswidget/generated/GeneratedGroup85Widget1.dart';
import 'package:flutterapp/taffy_appapp/generateddetailmessageswidget/generated/GeneratedStatusBarWidget1.dart';
import 'package:flutterapp/taffy_appapp/generateddetailmessageswidget/generated/GeneratedMenuWidget4.dart';
import 'package:flutterapp/taffy_appapp/generateddetailmessageswidget/generated/GeneratedOvalWidget69.dart';
import 'package:flutterapp/taffy_appapp/generateddetailmessageswidget/generated/GeneratedBottomDrawerWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generateddetailmessageswidget/generated/GeneratedMdisettingshelperWidget1.dart';
import 'package:flutterapp/taffy_appapp/generateddetailmessageswidget/generated/GeneratedBxbxarrowbackWidget2.dart';
import 'package:flutterapp/taffy_appapp/generateddetailmessageswidget/generated/GeneratedPopupWidget13.dart';
import 'package:flutterapp/taffy_appapp/generateddetailmessageswidget/generated/GeneratedDiscoverWidget7.dart';
import 'package:flutterapp/taffy_appapp/generateddetailmessageswidget/generated/GeneratedRectangle239Widget8.dart';
import 'package:flutterapp/taffy_appapp/generateddetailmessageswidget/generated/GeneratedGroup86Widget1.dart';
import 'package:flutterapp/taffy_appapp/generateddetailmessageswidget/generated/GeneratedGroup83Widget3.dart';
import 'package:flutterapp/taffy_appapp/generateddetailmessageswidget/generated/GeneratedRectangle242Widget.dart';

/* Frame DetailMessages
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailMessagesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: -44.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 290.0,
                child: GeneratedRectangle239Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.024;
                  double scaleX = (constraints.maxWidth * percentWidth) / 9.0;

                  double percentHeight = 0.011083743842364532;
                  double scaleY = (constraints.maxHeight * percentHeight) / 9.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.20266666666666666,
                        translateY: constraints.maxHeight * 0.22413793103448276,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedOvalWidget69())
                  ]);
                }),
              ),
              Positioned(
                left: 33.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 29.511629104614258,
                height: 27.97590446472168,
                child: GeneratedBxbxarrowbackWidget2(),
              ),
              Positioned(
                left: 316.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 36.0,
                child: GeneratedMdisettingshelperWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget1(),
              ),
              Positioned(
                left: 125.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 35.0,
                child: GeneratedDiscoverWidget7(),
              ),
              Positioned(
                left: -1.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 772.0,
                child: GeneratedPopupWidget13(),
              ),
              Positioned(
                left: -24.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 65.01998138427734,
                child: GeneratedGroup85Widget1(),
              ),
              Positioned(
                left: 69.0,
                top: 654.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 64.0,
                child: GeneratedGroup86Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 73.0,
                child: GeneratedMenuWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.13866666666666666;

                  final double height =
                      constraints.maxHeight * 0.06527093596059114;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.18133333333333335,
                        y: constraints.maxHeight * 0.06403940886699508,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup83Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: -3.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 812.0,
                child: GeneratedRectangle242Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 662.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 235.0,
                child: GeneratedBottomDrawerWidget(),
              )
            ]),
      ),
    ));
  }
}
