import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedCillistfilterWidget21.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedMdi_filter_listWidget13.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedVectorWidget164.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedCillistfilterWidget20.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedCillistfilterWidget22.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedCillistfilterWidget23.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedGroup35Widget3.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedDiscoverWidget11.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedBackgroundWidget3.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedMenuWidget8.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedPhoto3Widget3.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedPhoto2Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedMdi_find_replaceWidget3.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedMdi_filter_listWidget14.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedCillistfilterWidget19.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedMdi_filter_listWidget12.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedButtonsWidget3.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedMdi_filter_listWidget15.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedCillistfilterWidget18.dart';
import 'package:flutterapp/taffy_appapp/generatedlikewidget21/generated/GeneratedGroup82Widget.dart';

/* Frame Like
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLikeWidget21 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 344.0,
                child: GeneratedBackgroundWidget3(),
              ),
              Positioned(
                left: 43.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 296.0,
                height: 447.0,
                child: GeneratedPhoto3Widget3(),
              ),
              Positioned(
                left: 39.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 430.0,
                child: GeneratedPhoto2Widget3(),
              ),
              Positioned(
                left: 73.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 54.0,
                child: GeneratedDiscoverWidget11(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget12(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget18(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget19(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget13(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget20(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget21(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget14(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget22(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget23(),
              ),
              Positioned(
                left: 36.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 560.3469848632812,
                child: GeneratedGroup35Widget3(),
              ),
              Positioned(
                left: 109.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 120.00096893310547,
                child: GeneratedGroup82Widget(),
              ),
              Positioned(
                left: 305.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 331.0,
                child: GeneratedButtonsWidget3(),
              ),
              Positioned(
                left: 314.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedMdi_filter_listWidget15(),
              ),
              Positioned(
                left: 21.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedMdi_find_replaceWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.050666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 19.0;

                  double percentHeight = 0.023399014778325122;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8746666666666667,
                        translateY: constraints.maxHeight * 0.4396551724137931,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget164())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 73.0,
                child: GeneratedMenuWidget8(),
              )
            ]),
      ),
    ));
  }
}
