import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget38/generated/GeneratedMdi_navigate_nextWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget38/generated/GeneratedMdi_important_devicesWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget38/generated/GeneratedBaseWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget38/generated/GeneratedNextWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget38/generated/GeneratedPopupWidget17.dart';

/* Frame รูปโปรไฟล์
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget38 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -30.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 842.0,
                child: GeneratedBaseWidget3(),
              ),
              Positioned(
                left: 16.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 427.0,
                child: GeneratedPopupWidget17(),
              ),
              Positioned(
                left: 167.0,
                top: null,
                right: null,
                bottom: null,
                width: 47.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: 0.00, y: 310.50, z: 0, child: GeneratedNextWidget()),
              ),
              Positioned(
                left: 159.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedMdi_navigate_nextWidget(),
              ),
              Positioned(
                left: 155.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 68.0,
                child: GeneratedMdi_important_devicesWidget(),
              )
            ]),
      ),
    ));
  }
}
