import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldwidget/generated/GeneratedRectangle239Widget6.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldwidget/generated/GeneratedGroup125Widget.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldwidget/generated/GeneratedGroup91Widget.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldwidget/generated/GeneratedEmojionev1candyWidget4.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldwidget/generated/GeneratedMdi_searchWidget4.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldwidget/generated/GeneratedGroup92Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldwidget/generated/GeneratedMdi_menuWidget2.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldwidget/generated/GeneratedPopupWidget11.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldwidget/generated/GeneratedPopupWidget10.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldwidget/generated/GeneratedMenuChatWidget4.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldwidget/generated/GeneratedMenuChatWidget5.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldwidget/generated/GeneratedDiscoverWidget5.dart';

/* Frame TaffyGold
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTaffyGoldWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: -44.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 290.0,
                child: GeneratedRectangle239Widget6(),
              ),
              Positioned(
                left: 86.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 51.0,
                child: GeneratedDiscoverWidget5(),
              ),
              Positioned(
                left: 320.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedMdi_searchWidget4(),
              ),
              Positioned(
                left: -1.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 375.97674560546875,
                height: 584.0,
                child: GeneratedPopupWidget10(),
              ),
              Positioned(
                left: -1.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 661.0,
                child: GeneratedPopupWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.912;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.048,
                        y: constraints.maxHeight * 0.1416256157635468,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMenuChatWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: -26.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 691.0,
                child: GeneratedMenuChatWidget5(),
              ),
              Positioned(
                left: 31.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 26.033767700195312,
                child: GeneratedGroup91Widget(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 24.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -62.00,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width =
                          constraints.maxWidth * 0.4746666666666667;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * 0.184,
                            y: 0,
                            z: 0,
                            child: Container(
                              width: width,
                              child: GeneratedGroup92Widget(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.12653510538736978;

                  final double height =
                      constraints.maxHeight * 0.05727928142829482;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.09216715494791666,
                        y: constraints.maxHeight * 0.12757159453894704,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedEmojionev1candyWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 27.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 33.0,
                child: GeneratedMdi_menuWidget2(),
              ),
              Positioned(
                left: 32.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 26.0,
                child: GeneratedGroup125Widget(),
              )
            ]),
      ),
    ));
  }
}
