import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedGroup35Widget1.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedMdi_filter_listWidget6.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedPhoto2Widget1.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedCillistfilterWidget8.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedCillistfilterWidget11.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedCillistfilterWidget10.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedMdi_filter_listWidget7.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedMdi_filter_listWidget4.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedMenuWidget6.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedDiscoverWidget9.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedButtonsWidget1.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedCillistfilterWidget6.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedVectorWidget146.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedMdi_filter_listWidget5.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedPhoto3Widget1.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedCillistfilterWidget7.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedCillistfilterWidget9.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedBackgroundWidget1.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover19widget/generated/GeneratedMdi_find_replaceWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Discover 19
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDiscover19Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 817.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 344.0,
                child: GeneratedBackgroundWidget1(),
              ),
              Positioned(
                left: 43.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 296.0,
                height: 447.0,
                child: GeneratedPhoto3Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 430.0,
                child: GeneratedPhoto2Widget1(),
              ),
              Positioned(
                left: 73.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 54.0,
                child: GeneratedDiscoverWidget9(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget4(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget6(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget7(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget5(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget8(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget9(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget6(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget10(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget11(),
              ),
              Positioned(
                left: 36.0,
                top: 126.7758560180664,
                right: null,
                bottom: null,
                width: 310.0,
                height: 563.79736328125,
                child: GeneratedGroup35Widget1(),
              ),
              Positioned(
                left: 305.0,
                top: 332.0320129394531,
                right: null,
                bottom: null,
                width: 66.0,
                height: 328.9679870605469,
                child: GeneratedButtonsWidget1(),
              ),
              Positioned(
                left: 314.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedMdi_filter_listWidget7(),
              ),
              Positioned(
                left: 21.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedMdi_find_replaceWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.050666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 19.0;

                  double percentHeight = 0.023399026186696755;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      19.11700439453125;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8746666666666667,
                        translateY: constraints.maxHeight * 0.43965516854966724,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget146())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 73.0,
                child: GeneratedMenuWidget6(),
              )
            ]),
      ),
    ));
  }
}
