import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedGroupWidget58.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedGroupWidget65.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedGroupWidget63.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedGroupWidget62.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedGroupWidget56.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedVectorWidget357.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedPolygon2Widget1.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedVectorWidget355.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedGroupWidget57.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedGroupWidget66.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedGroupWidget64.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedGroupWidget55.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedGroupWidget60.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedVectorWidget360.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedPolygon1Widget1.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedGroupWidget54.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedVectorWidget358.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedVectorWidget356.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedEmojionev1candyWidget8.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedGroupWidget61.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedVectorWidget359.dart';
import 'package:flutterapp/taffy_appapp/generatedgoldwidget/generated/GeneratedGroupWidget67.dart';

/* Frame gold
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGoldWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedDiscoverGoldWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.0, -1.0),
              end: Alignment(0.0, 0.9999999999999998),
              stops: [0.0, 1.0],
              colors: [
                Color.fromARGB(255, 235, 217, 161),
                Color.fromARGB(255, 235, 217, 161)
              ],
            ),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 238, 71, 139),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 2.58047900390625;
                    double scaleX = (constraints.maxWidth * percentWidth) /
                        967.6796264648438;

                    double percentHeight = 0.8727201264480065;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        708.6487426757812;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                              constraints.maxWidth * 0.24054353841145834,
                          translateY:
                              constraints.maxHeight * 1.5779727127751693,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedPolygon2Widget1())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.024224934895833335;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 9.0843505859375;

                    double percentHeight = 0.011164101473803591;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        9.065250396728516;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.808,
                          translateY:
                              constraints.maxHeight * 0.29926108374384236,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget355())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.024224934895833335;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 9.0843505859375;

                    double percentHeight = 0.011164101473803591;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        9.065250396728516;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.2986666666666667,
                          translateY:
                              constraints.maxHeight * 0.29926108374384236,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget356())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.024224934895833335;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 9.0843505859375;

                    double percentHeight = 0.011164101473803591;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        9.065250396728516;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.568,
                          translateY:
                              constraints.maxHeight * 0.22167487684729065,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget357())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.024224934895833335;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 9.0843505859375;

                    double percentHeight = 0.011164101473803591;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        9.065250396728516;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                              constraints.maxWidth * 0.15466666666666667,
                          translateY:
                              constraints.maxHeight * 0.5394088669950738,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget358())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.024224934895833335;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 9.0843505859375;

                    double percentHeight = 0.011164101473803591;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        9.065250396728516;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.8426666666666667,
                          translateY:
                              constraints.maxHeight * 0.5726600985221675,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget359())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.024224934895833335;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 9.0843505859375;

                    double percentHeight = 0.011164101473803591;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        9.065250396728516;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                              constraints.maxWidth * 0.14133333333333334,
                          translateY:
                              constraints.maxHeight * 0.41995073891625617,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget360())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.23928955078125;

                    final double height =
                        constraints.maxHeight * 7.516644858374384e-8;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.17066666666666666,
                          y: constraints.maxHeight * 0.28201970443349755,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget54(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.23928955078125;

                    final double height =
                        constraints.maxHeight * 7.516644858374384e-8;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.2613333333333333,
                          y: constraints.maxHeight * 0.6366995073891626,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget55(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.5462054036458334,
                          y: constraints.maxHeight * 0.6304119842980296,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget56(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.12533333333333332,
                          y: constraints.maxHeight * 0.35344827586206895,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget57(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.745735107421875;

                    final double height =
                        constraints.maxHeight * 0.3435960215300762;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.152,
                          y: constraints.maxHeight * 0.29310344827586204,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget58(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 4.101358723958334;
                    double scaleX = (constraints.maxWidth * percentWidth) /
                        1538.009521484375;

                    double percentHeight = 1.5964535868226601;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 1296.3203125;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                              constraints.maxWidth * -1.4859075520833334,
                          translateY:
                              constraints.maxHeight * 0.7070083993996306,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedPolygon1Widget1())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.72,
                          y: constraints.maxHeight * 0.3891625615763547,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget60(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.456,
                          y: constraints.maxHeight * 0.3275862068965517,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget61(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.21066666666666667,
                          y: constraints.maxHeight * 0.479064039408867,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget62(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.7066666666666667,
                          y: constraints.maxHeight * 0.4938423645320197,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget63(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.17866666666666667,
                          y: constraints.maxHeight * 0.43103448275862066,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget64(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.32,
                          y: constraints.maxHeight * 0.35960591133004927,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget65(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.616,
                          y: constraints.maxHeight * 0.3485221674876847,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget66(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.49866666666666665,
                          y: constraints.maxHeight * 0.5332512315270936,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget67(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.5308498942057291;

                    final double height =
                        constraints.maxHeight * 0.2403025321772533;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.14933333333333335,
                          y: constraints.maxHeight * 0.47380355308795796,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedEmojionev1candyWidget8(),
                          ))
                    ]);
                  }),
                )
              ]),
        ),
      ),
    ));
  }
}
