import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatededit_profilewidget/generated/GeneratedWidget1.dart';
import 'package:flutterapp/taffy_appapp/generatededit_profilewidget/generated/GeneratedEditWidget.dart';
import 'package:flutterapp/taffy_appapp/generatededit_profilewidget/generated/GeneratedPopupWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatededit_profilewidget/generated/GeneratedContentContentBlockSmallWidget.dart';

/* Frame Edit_Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEdit_ProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 231, 69, 108),
                ),
              ),
              Positioned(
                left: 18.0,
                top: 812.0,
                right: 14.0,
                bottom: null,
                width: null,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 774.0,
                child: GeneratedPopupWidget1(),
              ),
              Positioned(
                left: null,
                top: 58.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 34.0,
                child: TransformHelper.translate(
                    x: -58.50, y: 0.00, z: 0, child: GeneratedWidget1()),
              ),
              Positioned(
                left: 22.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 860.0,
                child: GeneratedEditWidget(),
              )
            ]),
      ),
    ));
  }
}
