import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedGroupWidget38.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedGroupWidget48.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedGroupWidget47.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedGroupWidget40.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedGroupWidget49.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedGroupWidget51.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedGroupWidget52.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedEmojionev1candyWidget7.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedVectorWidget297.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedGroupWidget53.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedVectorWidget298.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedVectorWidget299.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedPolygon1Widget.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedGroupWidget41.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedVectorWidget300.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedGroupWidget37.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedVectorWidget296.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedGroupWidget46.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedVectorWidget295.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedPolygon2Widget.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedGroupWidget50.dart';
import 'package:flutterapp/taffy_appapp/generatedframewidget/generated/GeneratedGroupWidget39.dart';

/* Frame Frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrameWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedLoginsWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.0, -1.0),
              end: Alignment(0.0, 0.9999999999999998),
              stops: [0.0, 1.0],
              colors: [
                Color.fromARGB(255, 247, 86, 154),
                Color.fromARGB(255, 254, 115, 122)
              ],
            ),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 238, 71, 139),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 2.58047900390625;
                    double scaleX = (constraints.maxWidth * percentWidth) /
                        967.6796264648438;

                    double percentHeight = 0.8727201264480065;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        708.6487426757812;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                              constraints.maxWidth * 0.24054353841145834,
                          translateY:
                              constraints.maxHeight * 1.5779727127751693,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedPolygon2Widget())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.024224934895833335;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 9.0843505859375;

                    double percentHeight = 0.011164101473803591;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        9.065250396728516;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.808,
                          translateY:
                              constraints.maxHeight * 0.29926108374384236,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget295())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.024224934895833335;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 9.0843505859375;

                    double percentHeight = 0.011164101473803591;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        9.065250396728516;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.2986666666666667,
                          translateY:
                              constraints.maxHeight * 0.29926108374384236,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget296())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.024224934895833335;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 9.0843505859375;

                    double percentHeight = 0.011164101473803591;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        9.065250396728516;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.568,
                          translateY:
                              constraints.maxHeight * 0.22167487684729065,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget297())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.024224934895833335;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 9.0843505859375;

                    double percentHeight = 0.011164101473803591;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        9.065250396728516;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                              constraints.maxWidth * 0.15466666666666667,
                          translateY:
                              constraints.maxHeight * 0.5394088669950738,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget298())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.024224934895833335;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 9.0843505859375;

                    double percentHeight = 0.011164101473803591;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        9.065250396728516;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.8426666666666667,
                          translateY:
                              constraints.maxHeight * 0.5726600985221675,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget299())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.024224934895833335;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 9.0843505859375;

                    double percentHeight = 0.011164101473803591;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        9.065250396728516;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                              constraints.maxWidth * 0.14133333333333334,
                          translateY:
                              constraints.maxHeight * 0.41995073891625617,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget300())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.23928955078125;

                    final double height =
                        constraints.maxHeight * 7.516644858374384e-8;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.17066666666666666,
                          y: constraints.maxHeight * 0.28201970443349755,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget37(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.23928955078125;

                    final double height =
                        constraints.maxHeight * 7.516644858374384e-8;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.2613333333333333,
                          y: constraints.maxHeight * 0.6366995073891626,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget38(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.5462054036458334,
                          y: constraints.maxHeight * 0.6304119842980296,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget39(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.12533333333333332,
                          y: constraints.maxHeight * 0.35344827586206895,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget40(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.745735107421875;

                    final double height =
                        constraints.maxHeight * 0.3435960215300762;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.152,
                          y: constraints.maxHeight * 0.29310344827586204,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget41(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 4.101358723958334;
                    double scaleX = (constraints.maxWidth * percentWidth) /
                        1538.009521484375;

                    double percentHeight = 1.5964535868226601;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 1296.3203125;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                              constraints.maxWidth * -1.4859075520833334,
                          translateY:
                              constraints.maxHeight * 0.7070083993996306,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedPolygon1Widget())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.473962646484375;

                    final double height =
                        constraints.maxHeight * 0.2145510894324392;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.19259883626302082,
                          y: constraints.maxHeight * 0.4387536260294797,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedEmojionev1candyWidget7(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.72,
                          y: constraints.maxHeight * 0.3891625615763547,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget46(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.456,
                          y: constraints.maxHeight * 0.3275862068965517,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget47(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.21066666666666667,
                          y: constraints.maxHeight * 0.479064039408867,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget48(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.7066666666666667,
                          y: constraints.maxHeight * 0.4938423645320197,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget49(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.17866666666666667,
                          y: constraints.maxHeight * 0.43103448275862066,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget50(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.32,
                          y: constraints.maxHeight * 0.35960591133004927,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget51(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.616,
                          y: constraints.maxHeight * 0.3485221674876847,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget52(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.025375813802083334;

                    final double height =
                        constraints.maxHeight * 0.011669328060056189;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.49866666666666665,
                          y: constraints.maxHeight * 0.5332512315270936,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget53(),
                          ))
                    ]);
                  }),
                )
              ]),
        ),
      ),
    ));
  }
}
