import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedframe1widget/generated/GeneratedVectorWidget416.dart';
import 'package:flutterapp/taffy_appapp/generatedframe1widget/generated/GeneratedVectorWidget413.dart';
import 'package:flutterapp/taffy_appapp/generatedframe1widget/generated/GeneratedVectorWidget415.dart';
import 'package:flutterapp/taffy_appapp/generatedframe1widget/generated/GeneratedVectorWidget412.dart';
import 'package:flutterapp/taffy_appapp/generatedframe1widget/generated/GeneratedGroupWidget72.dart';
import 'package:flutterapp/taffy_appapp/generatedframe1widget/generated/GeneratedVectorWidget411.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatedframe1widget/generated/GeneratedGroupWidget69.dart';
import 'package:flutterapp/taffy_appapp/generatedframe1widget/generated/GeneratedGroupWidget70.dart';
import 'package:flutterapp/taffy_appapp/generatedframe1widget/generated/GeneratedGroupWidget71.dart';
import 'package:flutterapp/taffy_appapp/generatedframe1widget/generated/GeneratedGroupWidget73.dart';
import 'package:flutterapp/taffy_appapp/generatedframe1widget/generated/GeneratedDiscoverWidget16.dart';
import 'package:flutterapp/taffy_appapp/generatedframe1widget/generated/GeneratedVectorWidget414.dart';

/* Frame Frame1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 247, 86, 154),
              Color.fromARGB(255, 254, 115, 122)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 238, 71, 139),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.024224934895833335;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 9.0843505859375;

                  double percentHeight = 0.011164101473803591;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      9.065250396728516;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.808,
                        translateY: constraints.maxHeight * 0.29926108374384236,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget411())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.024224934895833335;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 9.0843505859375;

                  double percentHeight = 0.011164101473803591;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      9.065250396728516;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.2986666666666667,
                        translateY: constraints.maxHeight * 0.29926108374384236,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget412())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.024224934895833335;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 9.0843505859375;

                  double percentHeight = 0.011164101473803591;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      9.065250396728516;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.568,
                        translateY: constraints.maxHeight * 0.22167487684729065,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget413())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.024224934895833335;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 9.0843505859375;

                  double percentHeight = 0.011164101473803591;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      9.065250396728516;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.15466666666666667,
                        translateY: constraints.maxHeight * 0.5394088669950738,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget414())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.024224934895833335;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 9.0843505859375;

                  double percentHeight = 0.011164101473803591;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      9.065250396728516;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8426666666666667,
                        translateY: constraints.maxHeight * 0.5726600985221675,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget415())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.024224934895833335;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 9.0843505859375;

                  double percentHeight = 0.011164101473803591;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      9.065250396728516;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.14133333333333334,
                        translateY: constraints.maxHeight * 0.41995073891625617,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget416())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.23928955078125;

                  final double height =
                      constraints.maxHeight * 7.516644858374384e-8;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.17066666666666666,
                        y: constraints.maxHeight * 0.28201970443349755,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget69(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.23928955078125;

                  final double height =
                      constraints.maxHeight * 7.516644858374384e-8;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2613333333333333,
                        y: constraints.maxHeight * 0.6366995073891626,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget70(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.025375813802083334;

                  final double height =
                      constraints.maxHeight * 0.011669328060056189;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5462054036458334,
                        y: constraints.maxHeight * 0.6304119842980296,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget71(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.025375813802083334;

                  final double height =
                      constraints.maxHeight * 0.011669328060056189;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12533333333333332,
                        y: constraints.maxHeight * 0.35344827586206895,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget72(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 105.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 55.0,
                child: GeneratedDiscoverWidget16(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.304;

                  final double height =
                      constraints.maxHeight * 0.1182419537323449;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3466666666666667,
                        y: constraints.maxHeight * 0.33866995073891626,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget73(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
