import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget49/generated/GeneratedMdi_verified_userWidget5.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget49/generated/GeneratedGroup109Widget.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget49/generated/GeneratedGroup65Widget5.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget49/generated/GeneratedWidget51.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget49/generated/GeneratedVectorWidget205.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget49/generated/GeneratedPopupWidget20.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget49/generated/GeneratedWidget50.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget49/generated/GeneratedVectorWidget206.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget49/generated/GeneratedRectangle23Widget5.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget49/generated/GeneratedGroup110Widget.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget49/generated/GeneratedBaseWidget6.dart';

/* Frame การกรอง
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget49 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -30.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 842.0,
                child: GeneratedBaseWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 768.0,
                child: GeneratedPopupWidget20(),
              ),
              Positioned(
                left: 17.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 34.0,
                child: GeneratedWidget50(),
              ),
              Positioned(
                left: 17.0,
                top: 246.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 43.0,
                child: GeneratedRectangle23Widget5(),
              ),
              Positioned(
                left: 35.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 12.469605445861816,
                child: GeneratedGroup109Widget(),
              ),
              Positioned(
                left: 68.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 34.0,
                child: GeneratedWidget51(),
              ),
              Positioned(
                left: 16.5,
                top: 117.0,
                right: null,
                bottom: null,
                width: 343.5,
                height: 89.0,
                child: GeneratedGroup65Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.12597117106119793;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 47.23918914794922;

                  double percentHeight = 0.02908816595970116;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      23.619590759277344;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.792,
                        translateY: constraints.maxHeight * 0.15517241379310345,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget205())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.12597117106119793;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 47.23918914794922;

                  double percentHeight = 0.02908816595970116;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      23.619590759277344;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.792,
                        translateY: constraints.maxHeight * 0.2105911330049261,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget206())
                  ]);
                }),
              ),
              Positioned(
                left: 63.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_verified_userWidget5(),
              ),
              Positioned(
                left: 280.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 22.0,
                child: GeneratedGroup110Widget(),
              )
            ]),
      ),
    ));
  }
}
