import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget31/generated/GeneratedHttpswwwgooglecomWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget31/generated/GeneratedPopupWidget14.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget31/generated/GeneratedGroup65Widget.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget31/generated/GeneratedMdi_linkWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget31/generated/GeneratedBaseWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget31/generated/GeneratedMdi_verified_userWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget31/generated/GeneratedWidget32.dart';

/* Frame เพิ่มรูปโปรไฟล์
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget31 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -30.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 842.0,
                child: GeneratedBaseWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 768.0,
                child: GeneratedPopupWidget14(),
              ),
              Positioned(
                left: 76.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 34.0,
                child: GeneratedWidget32(),
              ),
              Positioned(
                left: 15.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 157.0,
                child: GeneratedGroup65Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 27.0,
                child: GeneratedHttpswwwgooglecomWidget(),
              ),
              Positioned(
                left: 63.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_verified_userWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 173.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_linkWidget(),
              )
            ]),
      ),
    ));
  }
}
