import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedloginswidget/generated/GeneratedGroup68Widget.dart';
import 'package:flutterapp/taffy_appapp/generatedloginswidget/generated/GeneratedBackgroundWidget5.dart';
import 'package:flutterapp/taffy_appapp/generatedloginswidget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/taffy_appapp/generatedloginswidget/generated/GeneratedEmojionev1candyWidget6.dart';
import 'package:flutterapp/taffy_appapp/generatedloginswidget/generated/GeneratedGroupWidget10.dart';
import 'package:flutterapp/taffy_appapp/generatedloginswidget/generated/GeneratedGroup61Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatedloginswidget/generated/GeneratedGroup62Widget.dart';

/* Frame Logins
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedBackgroundWidget5(),
              ),
              Positioned(
                left: -1.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 486.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 222.0,
                child: GeneratedGroup62Widget(),
              ),
              Positioned(
                left: 66.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 132.4883270263672,
                child: GeneratedGroup68Widget(),
              ),
              Positioned(
                left: 3058.0,
                top: -91.55549621582031,
                right: null,
                bottom: null,
                width: 82.46649932861328,
                height: 80.83304595947266,
                child: GeneratedEmojionev1candyWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.376;

                  final double height =
                      constraints.maxHeight * 0.1154535227808459;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5253333333333333,
                        y: constraints.maxHeight * 0.1416256157635468,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget10(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.38666666666666666;

                  final double height =
                      constraints.maxHeight * 0.12707947980006928;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.10666666666666667,
                        y: constraints.maxHeight * 0.21921182266009853,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup61Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
