import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generated2widget4/generated/GeneratedPopupWidget23.dart';
import 'package:flutterapp/taffy_appapp/generated2widget4/generated/GeneratedNextWidget1.dart';
import 'package:flutterapp/taffy_appapp/generated2widget4/generated/GeneratedBaseWidget9.dart';
import 'package:flutterapp/taffy_appapp/generated2widget4/generated/GeneratedRectangle20Widget7.dart';
import 'package:flutterapp/taffy_appapp/generated2widget4/generated/GeneratedMdi_verified_userWidget8.dart';
import 'package:flutterapp/taffy_appapp/generated2widget4/generated/GeneratedWidget63.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generated2widget4/generated/GeneratedGroup65Widget8.dart';
import 'package:flutterapp/taffy_appapp/generated2widget4/generated/GeneratedMdi_navigate_nextWidget1.dart';
import 'package:flutterapp/taffy_appapp/generated2widget4/generated/GeneratedMdi_verified_userWidget9.dart';
import 'package:flutterapp/taffy_appapp/generated2widget4/generated/GeneratedMdi_find_in_pageWidget.dart';

/* Frame กรองเบื้องต้น2
    Autogenerated by FlutLab FTF Generator
  */
class Generated2Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -30.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 842.0,
                child: GeneratedBaseWidget9(),
              ),
              Positioned(
                left: 15.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 427.0,
                child: GeneratedPopupWidget23(),
              ),
              Positioned(
                left: 16.0,
                top: 516.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 43.0,
                child: GeneratedRectangle20Widget7(),
              ),
              Positioned(
                left: 78.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 34.0,
                child: GeneratedWidget63(),
              ),
              Positioned(
                left: 63.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_verified_userWidget8(),
              ),
              Positioned(
                left: 167.0,
                top: null,
                right: null,
                bottom: null,
                width: 47.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: 0.00, y: 310.50, z: 0, child: GeneratedNextWidget1()),
              ),
              Positioned(
                left: 159.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedMdi_navigate_nextWidget1(),
              ),
              Positioned(
                left: 159.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 67.0,
                child: GeneratedMdi_find_in_pageWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 201.0,
                child: GeneratedGroup65Widget8(),
              ),
              Positioned(
                left: 63.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_verified_userWidget9(),
              )
            ]),
      ),
    ));
  }
}
