import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedCillistfilterWidget12.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedDiscoverWidget10.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedMdi_filter_listWidget10.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedMdi_filter_listWidget8.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedStatusBarDarkWidget.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedCillistfilterWidget15.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedCillistfilterWidget17.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedCillistfilterWidget13.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedMdi_filter_listWidget9.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedMdi_filter_listWidget11.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedPhoto2Widget2.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedCillistfilterWidget16.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedMenuWidget7.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedBottomDrawerWidget1.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedGroup35Widget2.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedButtonsWidget2.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedBackgroundWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedVectorWidget157.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedMdi_find_replaceWidget2.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedCillistfilterWidget14.dart';
import 'package:flutterapp/taffy_appapp/generateddiscover18widget/generated/GeneratedPhoto3Widget2.dart';

/* Frame Discover 18
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDiscover18Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -5.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 344.0,
                child: GeneratedBackgroundWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 73.0,
                child: GeneratedMenuWidget7(),
              ),
              Positioned(
                left: 43.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 296.0,
                height: 447.0,
                child: GeneratedPhoto3Widget2(),
              ),
              Positioned(
                left: 39.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 430.0,
                child: GeneratedPhoto2Widget2(),
              ),
              Positioned(
                left: 73.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 54.0,
                child: GeneratedDiscoverWidget10(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget8(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget12(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget13(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget9(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget14(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget15(),
              ),
              Positioned(
                left: 307.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedMdi_filter_listWidget10(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget16(),
              ),
              Positioned(
                left: 180.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedCillistfilterWidget17(),
              ),
              Positioned(
                left: 36.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 560.3469848632812,
                child: GeneratedGroup35Widget2(),
              ),
              Positioned(
                left: 305.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 331.0,
                child: GeneratedButtonsWidget2(),
              ),
              Positioned(
                left: 314.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedMdi_filter_listWidget11(),
              ),
              Positioned(
                left: 21.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedMdi_find_replaceWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 44.0,
                child: GeneratedStatusBarDarkWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.050666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 19.0;

                  double percentHeight = 0.023399014778325122;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8746666666666667,
                        translateY: constraints.maxHeight * 0.4396551724137931,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget157())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 295.0,
                child: GeneratedBottomDrawerWidget1(),
              )
            ]),
      ),
    ));
  }
}
