import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget17.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatedemojionev1candywidget/generated/GeneratedGroupWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget18.dart';
import 'package:flutterapp/taffy_appapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget12.dart';
import 'package:flutterapp/taffy_appapp/generatedemojionev1candywidget/generated/GeneratedGWidget.dart';
import 'package:flutterapp/taffy_appapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget14.dart';
import 'package:flutterapp/taffy_appapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget16.dart';
import 'package:flutterapp/taffy_appapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget15.dart';
import 'package:flutterapp/taffy_appapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget13.dart';
import 'package:flutterapp/taffy_appapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget11.dart';

/* Frame emojione-v1:candy
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEmojionev1candyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: TransformHelper.rotate(
            a: 0.83,
            b: 0.60,
            c: -0.55,
            d: 0.80,
            child: ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                width: 139.73260498046875,
                height: 136.96484375,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 0.3454139201067189;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) /
                                  48.265586853027344;

                          double percentHeight = 0.3785828923116961;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  51.85254669189453;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX:
                                    constraints.maxWidth * 0.6509667577976386,
                                translateY:
                                    constraints.maxHeight * 0.5786242687270057,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget11())
                          ]);
                        }),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 0.2220195957069581;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) /
                                  31.02337646484375;

                          double percentHeight = 0.378644667277472;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  51.86100769042969;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX:
                                    constraints.maxWidth * 0.6509487944110608,
                                translateY:
                                    constraints.maxHeight * 0.5787656994196161,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget12())
                          ]);
                        }),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 0.3385345163470094;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) /
                                  47.3043098449707;

                          double percentHeight = 0.38712131778869463;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  53.022010803222656;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX: constraints.maxWidth *
                                    0.0013552323057297961,
                                translateY: constraints.maxHeight *
                                    -0.0000038959738926917026,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget13())
                          ]);
                        }),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 0.338557557529793;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) /
                                  47.30752944946289;

                          double percentHeight = 0.19301745418514532;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  26.43660545349121;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX: constraints.maxWidth *
                                    -0.000002496563680984854,
                                translateY:
                                    constraints.maxHeight * 0.1959079265580883,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget14())
                          ]);
                        }),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 0.5657532020692074;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) /
                                  79.05416870117188;

                          double percentHeight = 0.5477527169844281;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  75.02286529541016;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX:
                                    constraints.maxWidth * 0.23423936687634506,
                                translateY:
                                    constraints.maxHeight * 0.17150150933676525,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget15())
                          ]);
                        }),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 0.3741636651249094;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) /
                                  52.28286361694336;

                          double percentHeight = 0.5476644272452442;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  75.01077270507812;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX:
                                    constraints.maxWidth * 0.2335551747875734,
                                translateY:
                                    constraints.maxHeight * 0.17143653143092433,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget16())
                          ]);
                        }),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 0.5245557310519577;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) /
                                  73.29753875732422;

                          double percentHeight = 0.4854849440649688;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  66.49436950683594;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX:
                                    constraints.maxWidth * 0.2755002557462089,
                                translateY:
                                    constraints.maxHeight * 0.17150131437519608,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget17())
                          ]);
                        }),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          double percentWidth = 0.3176322050652164;
                          double scaleX =
                              (constraints.maxWidth * percentWidth) /
                                  44.383575439453125;

                          double percentHeight = 0.4854477899602145;
                          double scaleY =
                              (constraints.maxHeight * percentHeight) /
                                  66.4892807006836;

                          return Stack(children: [
                            TransformHelper.translateAndScale(
                                translateX:
                                    constraints.maxWidth * 0.47975018553066134,
                                translateY:
                                    constraints.maxHeight * 0.17116167739586602,
                                translateZ: 0,
                                scaleX: scaleX,
                                scaleY: scaleY,
                                scaleZ: 1,
                                child: GeneratedVectorWidget18())
                          ]);
                        }),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          final double width =
                              constraints.maxWidth * 0.2714351249836746;

                          final double height =
                              constraints.maxHeight * 0.4850134155840915;

                          return Stack(children: [
                            TransformHelper.translate(
                                x: constraints.maxWidth * 0.3771220820143803,
                                y: constraints.maxHeight * 0.19942093907306135,
                                z: 0,
                                child: Container(
                                  width: width,
                                  height: height,
                                  child: GeneratedGroupWidget(),
                                ))
                          ]);
                        }),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          final double width =
                              constraints.maxWidth * 0.26617919641090443;

                          final double height =
                              constraints.maxHeight * 0.3952699036823004;

                          return Stack(children: [
                            TransformHelper.translate(
                                x: constraints.maxWidth * 0.5241533839525915,
                                y: constraints.maxHeight * 0.20608785881841257,
                                z: 0,
                                child: Container(
                                  width: width,
                                  height: height,
                                  child: GeneratedGWidget(),
                                ))
                          ]);
                        }),
                      )
                    ]),
              ),
            )));
  }
}
