import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget36/generated/GeneratedBaseWidget2.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget36/generated/GeneratedMdi_verified_userWidget2.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget36/generated/Generated0500Widget.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget36/generated/GeneratedWidget37.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget36/generated/GeneratedGroup65Widget2.dart';
import 'package:flutterapp/taffy_appapp/generatedwidget36/generated/GeneratedPopupWidget16.dart';

/* Frame อธิบาย
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget36 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -30.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 842.0,
                child: GeneratedBaseWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 768.0,
                child: GeneratedPopupWidget16(),
              ),
              Positioned(
                left: 71.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 34.0,
                child: GeneratedWidget37(),
              ),
              Positioned(
                left: 17.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 192.0,
                child: GeneratedGroup65Widget2(),
              ),
              Positioned(
                left: 63.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_verified_userWidget2(),
              ),
              Positioned(
                left: 288.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 28.0,
                child: Generated0500Widget(),
              )
            ]),
      ),
    ));
  }
}
