import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generated1widget2/generated/GeneratedMdi_find_in_pageWidget1.dart';
import 'package:flutterapp/taffy_appapp/generated1widget2/generated/GeneratedPopupWidget24.dart';
import 'package:flutterapp/taffy_appapp/generated1widget2/generated/GeneratedBaseWidget10.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generated1widget2/generated/GeneratedNextWidget2.dart';
import 'package:flutterapp/taffy_appapp/generated1widget2/generated/GeneratedGroup65Widget9.dart';
import 'package:flutterapp/taffy_appapp/generated1widget2/generated/GeneratedMdi_navigate_nextWidget2.dart';
import 'package:flutterapp/taffy_appapp/generated1widget2/generated/GeneratedLine5Widget2.dart';
import 'package:flutterapp/taffy_appapp/generated1widget2/generated/GeneratedLine6Widget1.dart';

/* Frame กรองเบื้องต้น1
    Autogenerated by FlutLab FTF Generator
  */
class Generated1Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -30.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 842.0,
                child: GeneratedBaseWidget10(),
              ),
              Positioned(
                left: 16.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 427.0,
                child: GeneratedPopupWidget24(),
              ),
              Positioned(
                left: 167.0,
                top: null,
                right: null,
                bottom: null,
                width: 47.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: 0.00, y: 310.50, z: 0, child: GeneratedNextWidget2()),
              ),
              Positioned(
                left: 159.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 53.0,
                child: GeneratedMdi_navigate_nextWidget2(),
              ),
              Positioned(
                left: 154.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 67.0,
                child: GeneratedMdi_find_in_pageWidget1(),
              ),
              Positioned(
                left: 56.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 243.0,
                height: 3.0,
                child: GeneratedLine5Widget2(),
              ),
              Positioned(
                left: 44.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 247.46957397460938,
                child: GeneratedGroup65Widget9(),
              ),
              Positioned(
                left: 66.0,
                top: 549.5,
                right: null,
                bottom: null,
                width: 52.0,
                height: 0.0,
                child: GeneratedLine6Widget1(),
              )
            ]),
      ),
    ));
  }
}
