import 'package:flutter/material.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldhomewidget/generated/GeneratedEditWidget1.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldhomewidget/generated/GeneratedDiscoverWidget3.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldhomewidget/generated/GeneratedEmojionev1candyWidget2.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldhomewidget/generated/GeneratedPopupWidget7.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldhomewidget/generated/GeneratedWidget16.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldhomewidget/generated/GeneratedGroup90Widget.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldhomewidget/generated/GeneratedMdi_searchWidget2.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldhomewidget/generated/GeneratedMenuChatWidget2.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldhomewidget/generated/GeneratedRectangle239Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldhomewidget/generated/GeneratedPopupWidget6.dart';
import 'package:flutterapp/taffy_appapp/generatedtaffygoldhomewidget/generated/GeneratedMdi_menuWidget.dart';

/* Frame TaffyGoldHOme
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTaffyGoldHOmeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: -44.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 290.0,
                child: GeneratedRectangle239Widget4(),
              ),
              Positioned(
                left: 86.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 51.0,
                child: GeneratedDiscoverWidget3(),
              ),
              Positioned(
                left: 320.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedMdi_searchWidget2(),
              ),
              Positioned(
                left: -1.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 375.97674560546875,
                height: 584.0,
                child: GeneratedPopupWidget6(),
              ),
              Positioned(
                left: 116.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 26.65217399597168,
                child: GeneratedGroup90Widget(),
              ),
              Positioned(
                left: -1.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 661.0,
                child: GeneratedPopupWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.912;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.048,
                        y: constraints.maxHeight * 0.1416256157635468,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMenuChatWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.12653510538736978;

                  final double height =
                      constraints.maxHeight * 0.05727928142829482;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.09216715494791666,
                        y: constraints.maxHeight * 0.12757159453894704,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedEmojionev1candyWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 27.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 33.0,
                child: GeneratedMdi_menuWidget(),
              ),
              Positioned(
                left: 978.0,
                top: 1103.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 599.0,
                child: GeneratedWidget16(),
              ),
              Positioned(
                left: 35.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 987.0,
                child: GeneratedEditWidget1(),
              )
            ]),
      ),
    ));
  }
}
